---
name: Dependabot auto-approve

on:
  workflow_call:
    inputs:
      actor:
        description: 'GitHub actor to check'
        required: true
        type: string
      token:
        required: true
        type: string

permissions:
  pull-requests: write

jobs:
  auto-approve:
    runs-on: ubuntu-latest
    if: ${{ inputs.actor }} == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.1.0

      - name: Approve the pull request
        run: gh pr review --approve "${{ github.event.pull_request.html_url }}"
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
