---
name: Dependabot auto-merge

on:
  workflow_call:
    inputs:
      actor:
        description: 'GitHub actor to check'
        required: true
        type: string

# permissions: write-all
permissions:
  pull-requests: write
  contents: write

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ inputs.actor }} == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.2.0

      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --admin "${{ github.event.pull_request.html_url }}"
        if: steps.metadata.outputs.update-type == 'version-update:semver-minor' || steps.metadata.outputs.update-type == 'version-update:semver-patch'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
